qb_host = "127.0.0.1"
qb_port = 8080
qb_username = "admin"
qb_password = "CHANGE_ME"
http_basic_auth_username = ""
http_basic_auth_password = ""
http_protocol_scheme = "http"
http_timeout = 300
title_bar_speed_format = "[D: {down_text}, U: {up_text}]"
log_file = "qbiremo_enhanced.log"
